### ISSUE TITLE
libprotobuf-c0 and build errors on Ubuntu 15.10

### ISSUE THREAD

**Issue by vpapaioannou** [camsas/Musketeer#1] opened 2016-05-26 11:41 UTC
Trying to "make dependecies" I get this message,

include/Makefile.common:39: SUFFIX not set, will default to root of source tree!
/home/hadoop/projects/musketeer/musketeer/scripts/setup.sh
+---------------------------------------------------------------------
| FETCHING & INSTALLING EXTERNAL DEPENDENCIES 
+---------------------------------------------------------------------
Detected Ubuntu...
--> OS COMPATIBILITY CHECK (Ubuntu 15.04)
Ubuntu 15.04 is compatible.                                [  OK  ]
Checking if necessary packages are installed...
--> Ubuntu PACKAGE CHECK
The following packages are required to run Musketeer, but are not currently installed: 
libprotobuf-c0-dev

Please install them using the following commmand: 
$ sudo apt-get install libprotobuf-c0-dev

Makefile:31: recipe for target 'ext/.ext-ok' failed
make: **\* [ext/.ext-ok] Error 1

Then as root, I have installed protobuf-c/protobuf-c from 
https://github.com/protobuf-c/protobuf-c.

I try again to "make dependencies" to not avail. Finally, when I try,

apt-get install libprotobuf-c0-dev

I get this message,

Reading package lists... Done
Building dependency tree  
Reading state information... Done
Note, selecting 'libprotobuf-c-dev' instead of 'libprotobuf-c0-dev'
libprotobuf-c-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

What should I do?

I have Ubuntu 15.04 as OS.

Thanks.

**Comment by ms705** [comment] 2016-05-26 23:35
Hi @vpapaioannou, 

Thanks for reporting this! Our build system currently assumes an Ubuntu 14.04 environment, and hence some packages names don't match those used in newer versions of Ubuntu.

In particular, the `libprotobuf-c0-dev` package was renamed to `libprotobuf-c1-dev`, and while you have correctly installed the dependency, the Musketeer build script does not realize this, because it is looking for `libprotobuf-c0-dev`.

The easiest way to fix this is to:
1. Edit [line 17 of `setup.sh`](https://github.com/camsas/Musketeer/blob/master/scripts/setup.sh#L17), and replace `libprotobuf-c0-dev` with `libprotobuf-c1-dev`.
2. Run `make dependencies` again.

Hopefully this should work! Alternatively, you could use Docker to get an Ubuntu 14.04 user-space inside a container on Ubuntu 15.10.

**Comment by vpapaioannou** [comment] 2016-05-27 10:10
Hi @ms705,

I made the change you suggested. The problem remains and I get this message, 

+---------------------------------------------------------------------
| FETCHING & INSTALLING EXTERNAL DEPENDENCIES 
+---------------------------------------------------------------------
Detected Ubuntu...
--> OS COMPATIBILITY CHECK (Ubuntu 15.04)
Ubuntu 15.04 is compatible.                                [  OK  ]
Checking if necessary packages are installed...
--> Ubuntu PACKAGE CHECK
dpkg-query: no packages found matching libprotobuf-c1-dev
The following packages are required to run Musketeer, but are not currently installed: 
libprotobuf-c1-dev

Please install them using the following commmand: 
$ sudo apt-get install libprotobuf-c1-dev

Makefile:31: recipe for target 'ext/.ext-ok' failed
make: **\* [ext/.ext-ok] Error 1

Running the command, `updatedb` and  then `locate libprotobuf-c1` I get this,

**/usr/share/doc/libprotobuf-c1
/usr/share/doc/libprotobuf-c1/changelog.Debian.gz
/usr/share/doc/libprotobuf-c1/copyright
/var/cache/apt/archives/libprotobuf-c1_1.0.2-1build1_amd64.deb
/var/lib/dpkg/info/libprotobuf-c1.list
/var/lib/dpkg/info/libprotobuf-c1.md5sums
/var/lib/dpkg/info/libprotobuf-c1.postinst
/var/lib/dpkg/info/libprotobuf-c1.postrm
/var/lib/dpkg/info/libprotobuf-c1.shlibs
/var/lib/dpkg/info/libprotobuf-c1.symbols**

and when I run `locate libprotobuf-c1-dev` the output list is empty.

Does musketeer search to another path for the libprotobuf-c1-dev than the one presented above? What do you think?

Thanks

**Comment by ms705** [comment] 2016-05-28 03:21
Hi @vpapaioannou,

I tried this myself in an Ubuntu 15.10 Docker container, and found that you actually need to change the package name to `libprotobuf-c-dev`, rather than `libprotobuf-c1-dev` (the development headers are called `libprotobuf-c-dev`, and the library is called `libprotobuf-c1`).

Once I change the script in this way, I get past the package check. However, things fail further down when the script tries to check out `glog` from Google Code. I think this is because the GLog repo has moved to GitHub; I'll look into fixing this.

**Comment by vpapaioannou** [comment] 2016-05-28 12:08
Thanks @ms705,

for your quick replies and your help in general. I will wait for your fix. However, it there is something that I can do to help you, let me know.

**Comment by ms705** [comment] 2016-05-30 17:38
Hi @vpapaioannou,

I pushed some general fixes (ae66f136ce661defcb85ec926fc883b468d3b155), which in combination with [this patch](https://gist.github.com/ms705/2d8bfd56619a932293b3c19aef2c21fd) (same `libprotobuf-c0-dev` rename to `libprotobuf-c-dev` as before) make things compile on Ubuntu 15.10 for me.

Can you give that a try and let us know if this fixes your build issues?

**Comment by vpapaioannou** [comment] 2016-05-31 09:10
Good morning @ms705,

I have re-cloned the repository and I have changed the `MUSKETEER_HOME/scripts/setup.sh` according to the patch manually. I have just changed the line about `GOOGLE_PKGS`.

The building goes well until the `GOOGLE GFLAGS LIBRARY` section of the `setup.sh` script, _lines > #220_. I have noticed that the library  `libgflags0` is being checked if it exists. However, for Ubuntu 15.04 it seems that the corresponding library is `libgflags2`.

I made the change and I got this output,

include/Makefile.common:39: SUFFIX not set, will default to root of source tree!
/home/hadoop/projects/musketeer/musketeer/scripts/setup.sh
+---------------------------------------------------------------------
| FETCHING & INSTALLING EXTERNAL DEPENDENCIES 
+---------------------------------------------------------------------
Detected Ubuntu...
--> OS COMPATIBILITY CHECK (Ubuntu 15.04)
Ubuntu 15.04 is compatible.                                [  OK  ]
Checking if necessary packages are installed...
--> Ubuntu PACKAGE CHECK
All required Ubuntu packages are installed.                [  OK  ]
--> GOOGLE GFLAGS LIBRARY
Already installed.                                         [  OK  ]
--> GOOGLE GLOG LIBRARY
Cloning into 'google-glog-git'...
remote: Counting objects: 1412, done.
remote: Total 1412 (delta 0), reused 0 (delta 0), pack-reused 1412
Receiving objects: 100% (1412/1412), 1.31 MiB | 574.00 KiB/s, done.
Resolving deltas: 100% (1009/1009), done.
Checking connectivity... done.
Building google-glog library.../home/hadoop/projects/musketeer/musketeer/ext/google-glog-git/missing: Unknown `--is-lightweight' option
Try`/home/hadoop/projects/musketeer/musketeer/ext/google-glog-git/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
                                                           [  OK  ]
google-glog library (vHEAD) was built in google-glog-git. 
Please run the following comamnds to install it: 

$ cd /home/hadoop/projects/musketeer/musketeer/ext/google-glog-git
$ sudo make install

... and then re-run.
Makefile:31: recipe for target 'ext/.ext-ok' failed
make: **\* [ext/.ext-ok] Error 1

Finally, I have executed the last two commands i.e. 
`cd /home/hadoop/projects/musketeer/musketeer/ext/google-glog-git` and
`sudo make install` which gave me this( _there is an error message at the end_),

(CDPATH="${ZSH_VERSION+.}:" && cd . && autoheader)
rm -f src/stamp-h1
touch src/config.h.in
cd . && /bin/bash ./config.status src/config.h
config.status: creating src/config.h
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -DNDEBUG -g -O2 -MT src/libglog_la-logging.lo -MD -MP -MF src/.deps/libglog_la-logging.Tpo -c -o src/libglog_la-logging.lo `test -f 'src/logging.cc' || echo './'`src/logging.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-logging.lo -MD -MP -MF src/.deps/libglog_la-logging.Tpo -c src/logging.cc  -fPIC -DPIC -o src/.libs/libglog_la-logging.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-logging.lo -MD -MP -MF src/.deps/libglog_la-logging.Tpo -c src/logging.cc -o src/libglog_la-logging.o >/dev/null 2>&1
mv -f src/.deps/libglog_la-logging.Tpo src/.deps/libglog_la-logging.Plo
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -DNDEBUG -g -O2 -MT src/libglog_la-raw_logging.lo -MD -MP -MF src/.deps/libglog_la-raw_logging.Tpo -c -o src/libglog_la-raw_logging.lo `test -f 'src/raw_logging.cc' || echo './'`src/raw_logging.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-raw_logging.lo -MD -MP -MF src/.deps/libglog_la-raw_logging.Tpo -c src/raw_logging.cc  -fPIC -DPIC -o src/.libs/libglog_la-raw_logging.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-raw_logging.lo -MD -MP -MF src/.deps/libglog_la-raw_logging.Tpo -c src/raw_logging.cc -o src/libglog_la-raw_logging.o >/dev/null 2>&1
mv -f src/.deps/libglog_la-raw_logging.Tpo src/.deps/libglog_la-raw_logging.Plo
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -DNDEBUG -g -O2 -MT src/libglog_la-vlog_is_on.lo -MD -MP -MF src/.deps/libglog_la-vlog_is_on.Tpo -c -o src/libglog_la-vlog_is_on.lo `test -f 'src/vlog_is_on.cc' || echo './'`src/vlog_is_on.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-vlog_is_on.lo -MD -MP -MF src/.deps/libglog_la-vlog_is_on.Tpo -c src/vlog_is_on.cc  -fPIC -DPIC -o src/.libs/libglog_la-vlog_is_on.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-vlog_is_on.lo -MD -MP -MF src/.deps/libglog_la-vlog_is_on.Tpo -c src/vlog_is_on.cc -o src/libglog_la-vlog_is_on.o >/dev/null 2>&1
mv -f src/.deps/libglog_la-vlog_is_on.Tpo src/.deps/libglog_la-vlog_is_on.Plo
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -DNDEBUG -g -O2 -MT src/libglog_la-utilities.lo -MD -MP -MF src/.deps/libglog_la-utilities.Tpo -c -o src/libglog_la-utilities.lo `test -f 'src/utilities.cc' || echo './'`src/utilities.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-utilities.lo -MD -MP -MF src/.deps/libglog_la-utilities.Tpo -c src/utilities.cc  -fPIC -DPIC -o src/.libs/libglog_la-utilities.o
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-utilities.lo -MD -MP -MF src/.deps/libglog_la-utilities.Tpo -c src/utilities.cc -o src/libglog_la-utilities.o >/dev/null 2>&1
mv -f src/.deps/libglog_la-utilities.Tpo src/.deps/libglog_la-utilities.Plo
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I./src  -I./src     -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare  -DNO_FRAME_POINTER  -DNDEBUG -g -O2 -MT src/libglog_la-demangle.lo -MD -MP -MF src/.deps/libglog_la-demangle.Tpo -c -o src/libglog_la-demangle.lo `test -f 'src/demangle.cc' || echo './'`src/demangle.cc
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./src -I./src -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -DNO_FRAME_POINTER -DNDEBUG -g -O2 -MT src/libglog_la-demangle.lo -MD -MP -MF src/.deps/libglog_la-demangle.Tpo -c src/demangle.cc  -fPIC -DPIC -o src/.libs/libglog_la-demangle.o
In file included from src/demangle.cc:38:0:
src/demangle.h:80:27: error: expected initializer before 'Demangle'
 bool GOOGLE_GLOG_DLL_DECL Demangle(const char _mangled, char *out, int out_size);
                           ^
Makefile:1198: recipe for target 'src/libglog_la-demangle.lo' failed
make: *_\* [src/libglog_la-demangle.lo] Error 1

What should I do?

**Comment by ms705** [comment] 2016-06-02 04:03
Hi @vpapaioannou,

Thanks for trying, and sorry this is still a problem! It turns out my patch was missing a package dependency (`libgoogle-glog-dev`), and the build system tried to build glog from source after failing to find the package.

To solve this, either:
1. apply the [updated patch](https://gist.github.com/ms705/2d8bfd56619a932293b3c19aef2c21fd) and re-run `make dependencies`; or
2. manually install the `libgoogle-glog-dev` package and re-run `make dependencies`.

**Comment by vpapaioannou** [comment] 2016-06-03 09:05
Hello again @ms705,

To sum up, after making the following  changes to MUSKETTER_HOME/scripts/setup.sh file,

**line 17:** 
`libprotobuf-c0-dev -> libprotobuf-c-dev`
addition of `libgoogle-glog-dev`

**line 223:**
`libflags0` -> `libflags2`

I run command `make dependencies` without problem,

include/Makefile.common:39: SUFFIX not set, will default to root of source tree!
/home/hadoop/projects/musketeer/Musketeer/scripts/setup.sh
+---------------------------------------------------------------------
| FETCHING & INSTALLING EXTERNAL DEPENDENCIES 
+---------------------------------------------------------------------
Detected Ubuntu...
--> OS COMPATIBILITY CHECK (Ubuntu 15.04)
Ubuntu 15.04 is compatible.                                [  OK  ]
Checking if necessary packages are installed...
--> Ubuntu PACKAGE CHECK
All required Ubuntu packages are installed.                [  OK  ]
--> GOOGLE GFLAGS LIBRARY
Already installed.                                         [  OK  ]
--> GOOGLE GLOG LIBRARY
Already installed!                                         [  OK  ]
--> Hadoop jars
--> GOOGLE PROTOCOL BUFFERS
Already installed.                                         [  OK  ]
--> CAKE BUILD TOOL
Cloning into 'cake-git'...
remote: Counting objects: 1233, done.
remote: Compressing objects: 100% (86/86), done.
remote: Total 1233 (delta 51), reused 0 (delta 0), pack-reused 1147
Receiving objects: 100% (1233/1233), 286.30 KiB | 230.00 KiB/s, done.
Resolving deltas: 100% (731/731), done.
Checking connectivity... done.
                                                           [  OK  ]
--> CPPLINT HELPER SCRIPT

However, the `make all` command fails,

include/Makefile.common:39: SUFFIX not set, will default to root of source tree!
rm -f build/tests/all_tests.txt
mkdir -p build/tests
touch build/tests/all_tests.txt
make  --no-print-directory -C /home/hadoop/projects/musketeer/Musketeer/src antlr
../include/Makefile.common:39: SUFFIX not set, will default to root of source tree!
antlr3 RLPlus.g
make  --no-print-directory -C /home/hadoop/projects/musketeer/Musketeer/src/base all
  SETUP   /home/hadoop/projects/musketeer/Musketeer/build/base
  GEN     /home/hadoop/projects/musketeer/Musketeer/src/generated-cxx/base/job_run.pb.h
  GENC    /home/hadoop/projects/musketeer/Musketeer/src/generated-cxx/base/job_run.pb.h
  PBC     /home/hadoop/projects/musketeer/Musketeer/build/base/job_run.pb.o
/bin/sh: 1: clang++: not found
../../include/Makefile.common:77: recipe for target '/home/hadoop/projects/musketeer/Musketeer/build/base/job_run.pb.o' failed
make[1]: **\* [/home/hadoop/projects/musketeer/Musketeer/build/base/job_run.pb.o] Error 127
rm /home/hadoop/projects/musketeer/Musketeer/src/generated-cxx/base/job_run.pb.cc
Makefile:37: recipe for target 'base' failed
make: **\* [base] Error 2

**Comment by ms705** [comment] 2016-06-03 16:47
@vpapaioannou You're seeing this error because we build Musketeer using Clang (see "`/bin/sh: 1: clang++: not found`"), rather than GCC, and hence `CXX` is set to `clang++`.

You can change this in `include/Makefile.config` (building with GCC also works), or install Clang on your machine (`apt-get install clang` should do it).

**Comment by vpapaioannou** [comment] 2016-06-05 10:49
Hello @ms705,

to this point both commands `make dependencies` and `make all` work fine. In the attached file you will find some amendments that I made to scripts/setup.sh and include/Makefile.config files in order to run without problem in case
1. the Ubuntu version is > 14.XX
2. and in case clang is not installed. By the way, there is an error in line https://github.com/camsas/Musketeer/blob/master/include/Makefile.config#L50. According to command `dpkg-query -l` there is not any `clang++` package. There is however `clang`. This error is also corrected.

Finally, I tried to test Musketeer and I got this error many times,

1 warning
java.io.FileNotFoundException: MUSKETEER_ROOT/edgescnt_code/edgescnt.jar (No such file or directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
    at sun.tools.jar.Main.run(Main.java:195)
    at sun.tools.jar.Main.main(Main.java:1288)

[musketeer.tar.gz](https://github.com/camsas/Musketeer/files/299287/musketeer.tar.gz)

**Comment by ms705** [comment] 2016-06-05 16:18
Hi @vpapaioannou,

Thanks for the patch -- I had a quick look over it and it seems like a good solution that we should include in the upstream code. However, two minor requests:
1. Can you submit the patch as a GitHub pull request? (Just fork the repo, commit your changes to your fork, and create a PR using the GitHub UI.) This will allow us to review and upstream it more conveniently, and will also preserve your identity as the contributor :)
2. I think changing `clang++` to `clang` in `Makefile.config` is not correct: while it may work, `clang++` is the binary that ought to be used to compile C++ code (Clang will emit a warning otherwise). The `clang++` binary [is provided by the `clang` package](http://packages.ubuntu.com/search?searchon=contents&keywords=clang%2B%2B&mode=exactfilename&suite=xenial&arch=any) in Ubuntu.

Finally, as for the runtime errors: it looks like either the target directory for the code generation is missing (here, `MUSKETEER_ROOT`, although this was intended to be a placeholder in the README), or the build process hasn't managed to construct a `.jar` file (i.e., it failed to compile the Java code).

To debug this, it might be easiest if you could share the complete console output from Musketeer with us (attach a text file to a response here). One thing to look at is whether you have the `openjdk-7-jdk` package installed, which is required for compiling Java code (OpenJDK 6 or 8 might also work).

**Comment by vpapaioannou** [comment] 2016-06-05 20:47
@ms705,
1. I made the pull request,
2. regarding clang++ I followed your suggestion and I made the corresponding changes into `Makefile.config` file,
3. I rerun the building process at a _14.04_ and I noticed that also `libgflags2` are needed instead of `libgflags0`.
4. during `make all` process I received these messages, 

Musketeer/src/scheduling/scheduler_dynamic.cc:599:31: warning: variable length arrays are a C99 feature [-Wvla-extension]
    uint32_t cost[num_ops + 1][num_ops + 1];

Musketeer/src/scheduling/scheduler_dynamic.cc:601:39: warning: variable length arrays are a C99 feature [-Wvla-extension]
    FmwType scheduled_fmw[num_ops + 1][num_ops + 1];
1. finally, you can find the output of the 
   `./build/musketeer --logtostderr --stderrthreshold=0 --run_daemon=false --root_dir=MUSKETEER_ROOT --force_framework=hadoop --dry_run -beer_query=tests/pagerank/page_rank.rap`
   command, [here](https://github.com/camsas/Musketeer/files/299504/logs.txt)

**Comment by ms705** [comment] 2016-06-06 16:43
Hi @vpapaioannou,

Thanks for the PR, we should be able to get that merged soon.

As for the remaining issue, we'll need to dig a bit deeper. The problem seems to be that while the Hadoop job code gets generated, no `.jar` files get built. I suspect either [this](https://github.com/camsas/Musketeer/blob/master/src/translation/translator_hadoop.cc#L1055-L1058) or [this](https://github.com/camsas/Musketeer/blob/master/src/translation/translator_hadoop.cc#L1061-L1063) command is failing.

Could you maybe add some additional logging around these invocations to see where the error comes from? For example, you could add `LOG(INFO) << "About to compile Java code"` and `LOG(INFO) << "About to build JAR"` in the appropriate places. Alternatively, you can check the return value of `std::system()`, which should be zero if things worked out correctly (`CHECK_EQ(ret, 0)` should do the trick and highlight which `system()` invocation is failing).

Also, can you check what files actually exist in, e.g., `MUSKETEER_ROOT/iter_tmp_code/`?

**Comment by vpapaioannou** [comment] 2016-06-07 15:12
Here comes the info you asked for. Regarding the `std::system()` I added a `CHECK_EQ( ret, 0))` for both of them which are located around lines 1064 - 1067. Moreover, I added 3 `LOG(INFO) << "About to compile Java code"` lines, one before the if-then-else statement and one for each branch e.g. you will notice that the else branch has been executed.

[musketeer.tar.gz](https://github.com/camsas/Musketeer/files/302911/musketeer.tar.gz)

**Comment by ms705** [comment] 2016-06-07 22:21
Thanks!

I think I know what the problem is -- can you try using an absolute path for the `--root_dir` flag? That's how we intend `MUSKETEER_ROOT` to be specified, and I suspect there are bits of code that don't play nicely with relative paths (e.g., this Java compilation, which is probably being executed with the working directory set _inside_ `MUSKETEER_ROOT`).

With a correct `--root_dir`, you should get JAR files.

**Comment by vpapaioannou** [comment] 2016-06-07 22:37
Where should I set this path?

**Comment by ms705** [comment] 2016-06-07 22:48
On the command line, i.e., when you run

```
$ ./build/musketeer --logtostderr --stderrthreshold=0 --run_daemon=false --root_dir=MUSKETEER_ROOT --force_framework=hadoop --dry_run -beer_query=tests/pagerank/page_rank.rap
```

it becomes

```
$ ./build/musketeer [...] --root_dir=/absolute/path/to/your/MUSKETEER_ROOT/ [...]
```

**Comment by vpapaioannou** [comment] 2016-06-08 16:11
I think that I have run successfully the command above. I attach the logs for you to verify it.

By the way I would like to ask you 2 questions. 
1. If I have questions regarding the system, who should I ask?
2. Do you have a tutorial or something similar how to use your system?

[musketeer.tar.gz](https://github.com/camsas/Musketeer/files/304717/musketeer.tar.gz)

**Comment by ms705** [comment] 2016-06-09 19:42
Yes, this looks like correct output! If you remove the `--dry_run` flag, Musketeer will try to actually run the job in Hadoop (it assumes that you have the Hadoop client binaries installed on the machine).

Regarding your questions:
1. GitHub issues (i.e., here) are probably the best way of asking questions about the system. There is an email address (`musketeer@camsas.org`) that reaches all the developers, but the discussion won't be public.
2. We don't currently have much beyond what's in the paper or in the README, in part because we all ended up working on other research projects after the initial open-source release. However, we're happy to answer questions and help with issues that you encounter; in the future, there might be better documentation, as a couple of people are looking at using Musketeer for new research ideas.

**Comment by ms705** [comment] 2016-06-09 19:43
I'll close this issue for now since the original problem is solved; thanks for highlighting it!

If you have other questions, feel free to open new issues.

**Closed as completed by ms705** 2016-06-09 19:43 UTC

**Comment by vpapaioannou** [comment] 2016-06-09 21:06
Fine. If you have the time( the other developers also), it would be great to provide some examples of how to use Musketeer for each front-end and why not for every back-end.

Thanks for your help, I wish you the best.
